#!/bin/bash
# Configuration Check for Production Authentication

echo "=== PRODUCTION AUTHENTICATION CONFIGURATION ==="
echo ""
echo "1. FRONTEND (Vercel) - needs VITE_API_BASE_URL"
echo "   Expected: VITE_API_BASE_URL=https://emploiplus-backend.onrender.com"
echo "   File: .env.production"
if [ -f .env.production ]; then
    echo "   Current:"
    grep VITE_API_BASE_URL .env.production || echo "   ❌ NOT FOUND"
fi
echo ""
echo "2. BACKEND (Render) - needs CORS_ORIGINS"
echo "   Expected: CORS_ORIGINS=https://emploiplus.vercel.app,http://localhost:5173,..."
echo "   Set in: Render Dashboard → Environment Variables"
echo ""
echo "3. BACKEND (Render) - needs JWT_SECRET and DATABASE_URL"
echo "   Expected: JWT_SECRET=<your-secret>"
echo "   Expected: DATABASE_URL=postgresql://<user>:<pass>@<host>/<db>"
echo "   Set in: Render Dashboard → Environment Variables"
echo ""
echo "4. ENDPOINTS TO TEST:"
echo "   POST https://emploiplus-backend.onrender.com/api/register"
echo "   POST https://emploiplus-backend.onrender.com/api/login"
echo "   GET  https://emploiplus-backend.onrender.com/api/users/me (with Bearer token)"
echo ""
echo "5. FRONTEND AUTH FLOW:"
echo "   Files: src/hooks/useAuth.ts, src/pages/LoginUser.tsx, src/pages/Register.tsx"
echo "   Status: ✓ Fixed to use VITE_API_BASE_URL"
echo ""
echo "=== CHECKLIST ==="
echo "[ ] Vercel: VITE_API_BASE_URL env var set to https://emploiplus-backend.onrender.com"
echo "[ ] Render: CORS_ORIGINS includes https://emploiplus.vercel.app"
echo "[ ] Render: JWT_SECRET is set"
echo "[ ] Render: DATABASE_URL is set to Supabase PostgreSQL"
echo "[ ] Test: Register at https://emploiplus.vercel.app/inscription"
echo "[ ] Test: Login at https://emploiplus.vercel.app/connexion"
echo ""
